require('./applicationMethod.js');
require('./chemicalProduct.js');
require('./company.js');
require('./companyGroup.js');
require('./fertilizer.js');
require('./form.js');
require('./machinery.js');
require('./mano-de-obra.js');
require('./region.js');
require('./season.js');
require('./seed.js');
require('./seedType.js');
require('./user.js');
require('./visit.js');
require('./work.js');
require('./specialist.js');

require('./products.js')
require('./categoryProduct.js')
require('./crop.js')
